//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace P5_1Dipl_MVC_UASD_Estudiante_ImageUpload.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Clientes
    {
        public int ClienteId { get; set; }
        [Required(ErrorMessage = "{0} es un campo obligatorio")]
        public string Nombres { get; set; }
        [Required(ErrorMessage = "{0} es un campo obligatorio")]
        public string Apellidos { get; set; }
        [Required(ErrorMessage = "{0} es un campo obligatorio")]
        public string Direccion { get; set; }
        [Required(ErrorMessage = "{0} es un campo obligatorio")]
        [DataType(DataType.EmailAddress)]
        public string Email { get; set; }
        [StringLength(10, MinimumLength = 10, ErrorMessage = "La propiedad {0} debe tener {1} caracteres de máximo y {2} de mínimo")]
        [Required(ErrorMessage = "{0} es un campo obligatorio")]
        public string Telefono { get; set; }
        [StringLength(10, MinimumLength = 10, ErrorMessage = "La propiedad {0} debe tener {1} caracteres de máximo y {2} de mínimo")]
        [Required(ErrorMessage = "{0} es un campo obligatorio")]
        public string Movil { get; set; }


        public string ImageUrl { get; set; }
    }
}
