//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace P5_1Dipl_MVC_UASD_Estudiante_ImageUpload.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Productos
    {
        public int ProductoId { get; set; }
        [Required(ErrorMessage = "{0} es un campo obligatorio")]
        public string producto { get; set; }
        [Required(ErrorMessage = "{0} es un campo obligatorio")]
        public string descripcion { get; set; }
        [Required(ErrorMessage = "{0} es un campo obligatorio")]
        public Nullable<int> CantExistencia { get; set; }
        public string ImageUrl { get; set; }
    }
}
